//
//  storeWord.swift
//  scrabbleTwoLetter
//
//  Created by Chris Hovey on 4/11/16.
//  Copyright © 2016 Chris Hovey. All rights reserved.
//

import Foundation

class StoreWord {
    private var _aa = ScrabbleWord(word: "Aa", partOfSpeech: "noun", definition: "Basaltic lava", image: "aa", wiki: "https://en.wikipedia.org/wiki/Lava#.CA.BBA.CA.BB.C4.81")
    private var _ab = ScrabbleWord(word: "Ab", partOfSpeech: "noun", definition: "Stomach muscle", image: "ab", wiki: "https://en.wikipedia.org/wiki/Abdomen")
    private var _ad = ScrabbleWord(word: "Ad", partOfSpeech: "noun", definition: "Advertisement", image: "ad", wiki: "https://en.wikipedia.org/wiki/Advertising")
    private var _ae = ScrabbleWord(word: "Ae", partOfSpeech: "adjective", definition: "One (Scotland)", image: "ae", wiki: "https://en.wiktionary.org/wiki/ae#Etymology_1")//https://pixabay.com/en/bagpiper-loch-ness-kilt-tartan-1319161/
    private var _ag = ScrabbleWord(word: "Ag", partOfSpeech: "adjective", definition: "Relating to agriculture", image: "ag", wiki: "https://en.wikipedia.org/wiki/Agriculture")
    private var _ah = ScrabbleWord(word: "Ah", partOfSpeech: "interjection", definition: "Used to express realization or happiness", image: "ah", wiki: "https://en.wiktionary.org/wiki/ah#Interjection")
    private var _ai = ScrabbleWord(word: "Ai", partOfSpeech: "noun", definition: "Three clawed sloth", image: "ai", wiki: "https://en.wikipedia.org/wiki/Maned_sloth")
    private var _al = ScrabbleWord(word: "Al", partOfSpeech: "noun", definition: "Indian shrub", image: "al", wiki: "https://en.wiktionary.org/wiki/al#Noun")
    private var _am = ScrabbleWord(word: "Am", partOfSpeech: "verb", definition: "To exist", image: "am", wiki: "https://en.wikipedia.org/wiki/Cogito_ergo_sum")
    private var _an = ScrabbleWord(word: "An", partOfSpeech: "indef. article", definition: "Indefinite article placed before words beginning with a vowel sound", image: "an", wiki: "https://en.wikipedia.org/wiki/English_articles#Indefinite_article")//https://pixabay.com/en/ant-cistus-flowers-1203494/
    private var _ar = ScrabbleWord(word: "Ar", partOfSpeech: "noun", definition: "Letter R", image: "ar", wiki: "https://en.wikipedia.org/wiki/R")//https://upload.wikimedia.org/wikipedia/commons/b/be/Bonney%2C_Anne_%281697-1720%29.jpg
    private var _as = ScrabbleWord(word: "As", partOfSpeech: "adverb", definition: "Used in comparing", image: "as", wiki: "https://en.wiktionary.org/wiki/as#Adverb")
    private var _at = ScrabbleWord (word: "At", partOfSpeech: "preposition", definition: "Expressing time or place", image: "at", wiki: "https://en.wiktionary.org/wiki/at#Preposition")
    private var _aw = ScrabbleWord(word: "Aw", partOfSpeech: "exclamation", definition: "Way of expressing sympathy or protest", image: "aw", wiki: "https://en.wiktionary.org/wiki/aw#Interjection")//https://pixabay.com/en/child-face-pouting-stroller-1377126/
    private var _ax = ScrabbleWord(word: "Ax", partOfSpeech: "noun", definition: "Tool used to chop wood", image: "ax", wiki: "https://en.wikipedia.org/wiki/Axe")//https://pixabay.com/static/uploads/photo/2015/10/12/14/56/axe-984008_960_720.jpg
    private var _ay = ScrabbleWord(word: "Ay", partOfSpeech: "exclamation", definition: "Affirmative answer", image: "ay", wiki: "https://en.wikipedia.org/wiki/Yes_and_no#Colloquial_forms")
    private var _ba = ScrabbleWord(word: "Ba", partOfSpeech: "noun", definition: "In ancient Egypt this was one of five parts of the soul", image: "ba", wiki: "https://en.wikipedia.org/wiki/Ancient_Egyptian_concept_of_the_soul")
    private var _be = ScrabbleWord(word: "Be", partOfSpeech: "verb", definition: "Exist, first person singular", image: "be", wiki: "https://en.wikipedia.org/wiki/The_Creation_of_Adam")
    private var _bi = ScrabbleWord(word: "Bi", partOfSpeech: "adjective", definition: "Bisexual", image: "bi", wiki: "https://en.wikipedia.org/wiki/Bisexuality")
    private var _bo = ScrabbleWord(word: "Bo", partOfSpeech: "noun", definition: "Pal", image: "bo", wiki: "https://en.wiktionary.org/wiki/bo#Noun")
    private var _by = ScrabbleWord(word: "By", partOfSpeech: "adverb", definition: "Near or through", image: "by", wiki: "https://en.wiktionary.org/wiki/by#Preposition")
    private var _de = ScrabbleWord(word: "De", partOfSpeech: "preposition", definition: "From, used in names", image: "de", wiki: "https://en.wikipedia.org/wiki/Miguel_de_Cervantes")//https://en.wikipedia.org/wiki/Miguel_de_Cervantes
    private var _do = ScrabbleWord(word: "Do", partOfSpeech: "verb", definition: "To perform an action", image: "do", wiki: "https://en.wikipedia.org/wiki/We_Can_Do_It!")
    private var _ed = ScrabbleWord(word: "Ed", partOfSpeech: "noun", definition: "Education", image: "ed", wiki: "https://en.wikipedia.org/wiki/Education")
    private var _ef = ScrabbleWord(word: "Ef", partOfSpeech: "noun", definition: "Letter F", image: "ef", wiki: "https://en.wikipedia.org/wiki/F")
    private var _eh = ScrabbleWord(word: "Eh", partOfSpeech: "interjection", definition: "Used when a listener does not understand something", image: "eh", wiki: "https://en.wikipedia.org/wiki/Eh") //https://en.wikipedia.org/wiki/Flag_of_Canada
    private var _el = ScrabbleWord(word: "El", partOfSpeech: "noun", definition: "Letter L", image: "el", wiki: "https://en.wikipedia.org/wiki/L")
    private var _em = ScrabbleWord(word: "Em", partOfSpeech: "noun", definition: "Printer's measurement", image: "em", wiki: "https://en.wikipedia.org/wiki/Em_(typography)")
    private var _en = ScrabbleWord(word: "En", partOfSpeech: "noun", definition: "Half an em", image: "en", wiki: "https://en.wikipedia.org/wiki/En_(typography)")
    private var _er = ScrabbleWord(word: "Er", partOfSpeech: "interjection", definition: "Sound indicating hesitation", image: "er", wiki: "https://en.wiktionary.org/wiki/er#Interjection")
    private var _es = ScrabbleWord(word: "Es", partOfSpeech: "noun", definition: "Letter S", image: "es", wiki: "https://en.wikipedia.org/wiki/S")
    private var _et = ScrabbleWord(word: "Et", partOfSpeech: "verb", definition: "Past tense of eat", image: "et", wiki: "https://en.wiktionary.org/wiki/et#Etymology_2")
    private var _ex = ScrabbleWord(word: "Ex", partOfSpeech: "noun", definition: "Letter X", image: "ex", wiki: "https://en.wikipedia.org/wiki/X")
    private var _fa = ScrabbleWord(word: "Fa", partOfSpeech: "noun", definition: "Fourth note in music scale", image: "fa", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge")
    private var _fe = ScrabbleWord(word: "Fe", partOfSpeech: "noun", definition: "Hebrew letter, pronounced as 'Ph' or 'F'", image: "fe", wiki: "https://en.wikipedia.org/wiki/Pe_(letter)#Fe")    //https://commons.wikimedia.org/wiki/File:Hebrew_letter_pe_freefonts.svg
    private var _gi = ScrabbleWord(word: "Gi", partOfSpeech: "noun", definition: "Clothing worn for Judo", image: "gi", wiki: "https://en.wikipedia.org/wiki/Judogi") //pixabay
    private var _go = ScrabbleWord(word: "Go", partOfSpeech: "verb", definition: "To depart", image: "go", wiki: "https://en.wikipedia.org/wiki/Go_(verb)")    //pexel
    private var _ha = ScrabbleWord(word: "Ha", partOfSpeech: "exclamation", definition: "A sound made when surprised", image: "ha", wiki: "https://en.wiktionary.org/wiki/ha#Interjection")  //pixabay
    private var _he = ScrabbleWord(word: "He", partOfSpeech: "noun", definition: "Male", image: "he", wiki: "https://en.wikipedia.org/wiki/He") //pixabay
    private var _hi = ScrabbleWord(word: "Hi", partOfSpeech: "exclamation", definition: "Used as a greeting", image: "hi", wiki: "https://en.wiktionary.org/wiki/hi#Interjection") //publicdomainpictures.net
    private var _hm = ScrabbleWord(word: "Hm", partOfSpeech: "interjection", definition: "Denotes pondering", image: "hm", wiki: "https://en.wiktionary.org/wiki/hm#Interjection") //https://pixabay.com/static/uploads/photo/2016/04/01/23/35/art-1301872_960_720.png
    private var _ho = ScrabbleWord(word: "Ho", partOfSpeech: "interjection", definition: "Used to bring attention, i.e. by Santa", image: "ho", wiki: "https://en.wikipedia.org/wiki/Ho_ho_ho") //pixabay
    private var _id = ScrabbleWord(word: "Id", partOfSpeech: "noun", definition: "Part of psyche desiring pleasure, Sigmund Freud theory", image: "id", wiki: "https://en.wikipedia.org/wiki/Id,_ego_and_super-ego#Id")  //pixabay
    private var _if = ScrabbleWord(word: "If", partOfSpeech: "conjunction", definition: "In the event that", image: "if", wiki: "https://en.wikipedia.org/wiki/Flying_pig")    //pixabay https://pixabay.com/en/graffiti-funny-building-painted-386495/
    private var _in = ScrabbleWord(word: "In", partOfSpeech: "preposition", definition: "Inside", image: "in", wiki: "https://en.wikipedia.org/wiki/Arnolfini_Portrait") // https://pixabay.com/en/belly-painting-baby-pregnant-409794/
    private var _is = ScrabbleWord(word: "Is", partOfSpeech: "verb", definition: "Third person singular of be", image: "is", wiki: "https://en.wikipedia.org/wiki/Life") //https://pixabay.com/en/life-is-beautiful-courage-joy-hope-905867/
    private var _it = ScrabbleWord(word: "It", partOfSpeech: "pronoun", definition: "Designated person in a child's game", image: "it", wiki: "https://en.wikipedia.org/wiki/Tag_(game)")//https://pixabay.com/en/blindfolded-chase-game-search-kids-37705/
    private var _jo = ScrabbleWord(word: "Jo", partOfSpeech: "noun", definition: "Sweetheart, used in Scotland", image: "jo", wiki: "https://en.wiktionary.org/wiki/jo#Noun")
    private var _ka = ScrabbleWord(word: "Ka", partOfSpeech: "noun", definition: "Part of spirit which remains in a mummy", image: "ka", wiki: "https://en.wikipedia.org/wiki/Ancient_Egyptian_concept_of_the_soul#Ka_.28vital_spark.29")
    private var _ki = ScrabbleWord(word: "Ki", partOfSpeech: "noun", definition: "Synonymous with qi", image: "ki", wiki: "https://en.wikipedia.org/wiki/Qi")
    private var _la = ScrabbleWord(word: "La", partOfSpeech: "noun", definition: "Sixth note in music scale", image: "la", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge") //https://pixabay.com/en/piano-midi-music-musical-773735/
    private var _li = ScrabbleWord(word: "Li", partOfSpeech: "noun", definition: "Chinese measurement of distance, about .5 km", image: "li", wiki: "https://en.wikipedia.org/wiki/Li_(unit)") //https://www.pexels.com/photo/mountains-clouds-historical-great-wall-of-china-19872/
    private var _lo = ScrabbleWord(word: "Lo", partOfSpeech: "exclamation", definition: "Said when desiring attention, used in religous texts", image: "lo", wiki: "https://en.wiktionary.org/wiki/lo#Interjection") //https://pixabay.com/en/moses-jesus-wanderer-prophet-145721/
    private var _ma = ScrabbleWord(word: "Ma", partOfSpeech: "noun", definition: "Mother", image: "ma", wiki: "https://en.wikipedia.org/wiki/Mother") //https://www.pexels.com/photo/woman-female-girl-child-8986/
    private var _me = ScrabbleWord(word: "Me", partOfSpeech: "pronoun", definition: "Referring to self", image: "me", wiki: "https://en.wiktionary.org/wiki/me#Pronoun")//https://pixabay.com/en/penguin-zoo-conceited-844834/
    private var _mi = ScrabbleWord(word: "Mi", partOfSpeech: "noun", definition: "Third note in music scale", image: "mi", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge")
    private var _mm = ScrabbleWord(word: "Mm", partOfSpeech: "interjection", definition: "Used to convey one's pleasure", image: "mm", wiki: "https://en.wiktionary.org/wiki/mm#Interjection")//https://pixabay.com/en/ice-man-happy-eating-relax-party-375361/
    private var _mo = ScrabbleWord(word: "Mo", partOfSpeech: "noun", definition: "Short amount of time", image: "mo", wiki: "https://en.wikipedia.org/wiki/Moment_(time)") //https://pixabay.com/en/hourglass-time-pressure-time-708574/
    private var _mu = ScrabbleWord(word: "Mu", partOfSpeech: "noun", definition: "12th letter of the Greek alphabet", image: "mu", wiki: "https://en.wikipedia.org/wiki/Mu_(letter)") //https://commons.wikimedia.org/wiki/File:Mu_uc_lc.svg
    private var _my = ScrabbleWord(word: "My", partOfSpeech: "pronoun", definition: "Possessive I", image: "my", wiki: "https://en.wiktionary.org/wiki/my#Etymology_1") //http://digitalcollections.nypl.org/items/510d47df-f072-a3d9-e040-e00a18064a99
    private var _na = ScrabbleWord(word: "Na", partOfSpeech: "adverb", definition: "Not", image: "na", wiki: "https://en.wiktionary.org/wiki/na#Interjection") //https://www.pexels.com/photo/hand-thumbs-up-thumb-black-and-white-8252/
    private var _ne = ScrabbleWord(word: "Ne", partOfSpeech: "adjective", definition: "Birthname - Marilyn Monroe, ne Norma Mortenson", image: "ne", wiki: "https://en.wikipedia.org/wiki/Given_name#Name_at_birth") //https://commons.wikimedia.org/wiki/File:Marilyn_Monroe_photo_pose_Seven_Year_Itch.jpg
    private var _no = ScrabbleWord(word: "No", partOfSpeech: "determiner", definition: "None", image: "no", wiki: "https://en.wikipedia.org/wiki/Yes_and_no") //https://pixabay.com/en/no-hunting-sign-no-hunting-fence-1110491/   https://pixabay.com/en/stop-no-photo-no-photographing-hand-565609/
    private var _nu = ScrabbleWord(word: "Nu", partOfSpeech: "noun", definition: "13th letter of the Greek alphabet", image: "nu", wiki: "https://en.wikipedia.org/wiki/Nu_(letter)") //https://commons.wikimedia.org/wiki/File:Nu_uc_lc.svg
    private var _od = ScrabbleWord(word: "Od", partOfSpeech: "noun", definition: "Odic force, hypothetical force believed to transcend throughout nature", image: "od", wiki: "https://en.wikipedia.org/wiki/Odic_force") //https://pixabay.com/en/star-wars-flower-soldier-dark-1176168/
    private var _oe = ScrabbleWord(word: "Oe", partOfSpeech: "noun", definition: "Winds from the Faroe Islands", image: "oe", wiki: "https://en.wikipedia.org/wiki/Faroe_Islands#Climate") //https://pixabay.com/en/crooklets-beach-cornwall-bude-1313636/
    private var _of = ScrabbleWord(word: "Of", partOfSpeech: "preposition", definition: "Indicates belonging to something else", image: "of", wiki: "https://en.wiktionary.org/wiki/of#Preposition") //http://res.cloudinary.com/di6su8dza/image/upload/v1463118575/puzzle-654110_1280_s51zu6.jpg
    private var _oh = ScrabbleWord(word: "Oh", partOfSpeech: "exclamation", definition: "Exclamed during moments of sorrow, happiness, or anger", image: "oh", wiki: "https://en.wiktionary.org/wiki/oh")//https://pixabay.com/en/photographer-man-hands-characters-1210218/
    private var _oi = ScrabbleWord(word: "Oi", partOfSpeech: "exclamation", definition: "Said to try to gain a person's attention", image: "oi", wiki: "https://en.wikipedia.org/wiki/Oi_(interjection)") //https://www.flickr.com/photos/prblmtkx/22845310843/in/photolist-ANLbZH-uctXYG-ow8ti1-qbNw3e-otvM2c-ornWVj-ouXAsB-obP2U8-oeZbCd-obMVPW-of27Ad-owHJLB-odFGDZ-oc7Jtb-osYxmL-obZ8Pg-ouXTf6-odjQmA-orp4vG-obWjz9-otsmBh-ouWeWh-of2s75-odZsVQ-odZFm1-ovh91m-osYcuw-obw2U2-of27Pu-odueE8-obVozh-ouKMNY-osHE4n-oc8Qhc-odtk3M-otpimJ-oqXMjy-owWeR6-osUR5i-osHoGk-ouKT7y-osPS5u-ovhsbj-ot7LrM-obv6HZ-otcwpP-otoDKj-otha2w-oc8ufv-ouXWAz
    private var _om = ScrabbleWord(word: "Om", partOfSpeech: "noun", definition: "Sound made during meditation", image: "om", wiki: "https://en.wikipedia.org/wiki/Om")//https://www.pexels.com/photo/relaxation-relaxing-meditation-yoga-12344/
    private var _on = ScrabbleWord(word: "On", partOfSpeech: "preposition", definition: "In contact with another object", image: "on", wiki: "https://en.wiktionary.org/wiki/on#Adjective")//https://www.pexels.com/photo/mountains-nature-sky-sunny-6629/
    private var _op = ScrabbleWord(word: "Op", partOfSpeech: "noun", definition: "Type of art with optical illusions", image: "op", wiki: "https://en.wikipedia.org/wiki/Op_art")//https://pixabay.com/en/optical-illusion-chessboard-tunnel-155520/
    private var _or = ScrabbleWord(word: "Or", partOfSpeech: "noun", definition: "Color of gold used in armorial bearings during the middle ages", image: "or", wiki: "https://en.wikipedia.org/wiki/Or_(heraldry)")//https://pixabay.com/en/benferri-coat-of-arms-heraldry-906563/
    private var _os = ScrabbleWord(word: "Os", partOfSpeech: "noun", definition: "A bone", image: "os", wiki: "https://en.wiktionary.org/wiki/os#English")//https://pixabay.com/en/bone-animal-decay-skeleton-nature-949077/
    private var _ow = ScrabbleWord(word: "Ow", partOfSpeech: "exclamation", definition: "Said when one feels abrupt pain", image: "ow", wiki: "https://en.wiktionary.org/wiki/ow#Interjection")//https://pixabay.com/en/doctor-pain-vaccination-shot-arm-673578/
    private var _ox = ScrabbleWord(word: "Ox", partOfSpeech: "noun", definition: "Castrated male cattle", image: "ox", wiki: "https://en.wikipedia.org/wiki/Ox")//https://pixabay.com/en/swot-up-cattle-farm-nature-1261538/
    private var _oy = ScrabbleWord(word: "Oy", partOfSpeech: "exclamation", definition: "variable of oi", image: "oy", wiki: "https://en.wikipedia.org/wiki/Town_crier")
    private var _pa = ScrabbleWord(word: "Pa", partOfSpeech: "noun", definition: "Father", image: "pa", wiki: "https://en.wikipedia.org/wiki/Father") //https://pixabay.com/en/father-son-smile-laugh-happy-dad-849092/
    private var _pe = ScrabbleWord(word: "Pe", partOfSpeech: "noun", definition: "Hebrew letter, pronounced as 'P'", image: "pe", wiki: "https://en.wikipedia.org/wiki/Pe_(letter)")
    private var _pi = ScrabbleWord(word: "Pi", partOfSpeech: "noun", definition: "16th letter of Greek alphabet", image: "pi", wiki: "https://en.wikipedia.org/wiki/Pi_(letter)")//https://pixabay.com/en/pi-symbol-letter-mathematics-math-1327145/
    private var _qi = ScrabbleWord(word: "Qi", partOfSpeech: "noun", definition: "A life force in Chinesse medicine which flows throughout the body", image: "qi", wiki: "https://en.wikipedia.org/wiki/Qi")//https://www.pexels.com/photo/people-festival-sitting-freedom-50709/
    private var _re = ScrabbleWord(word: "Re", partOfSpeech: "noun", definition: "Second note in music scale", image: "re", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge")
    private var _sh = ScrabbleWord(word: "Sh", partOfSpeech: "interjection", definition: "Used when desiring silence", image: "sh", wiki: "https://en.wiktionary.org/wiki/sh#Interjection")//https://pixabay.com/en/person-human-child-girl-blond-976759/
    private var _si = ScrabbleWord(word: "Si", partOfSpeech: "noun", definition: "Seventh note in music scale, also known as Ti", image: "si", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge")
    private var _so = ScrabbleWord(word: "So", partOfSpeech: "noun", definition: "Fifth note in music scale", image: "so", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge")
    private var _ta = ScrabbleWord(word: "Ta", partOfSpeech: "exclamation", definition: "Thank you", image: "ta", wiki: "https://en.wiktionary.org/wiki/ta#Interjection")//https://pixabay.com/en/thanks-gratitude-smile-appreciation-1209247/
    private var _ti = ScrabbleWord(word: "Ti", partOfSpeech: "noun", definition: "Seventh note in music scale", image: "ti", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge")
    private var _to = ScrabbleWord(word: "To", partOfSpeech: "preposition", definition: "Indicates moving toward something", image: "to", wiki: "https://en.wiktionary.org/wiki/to#Particle")
    private var _uh = ScrabbleWord(word: "Uh", partOfSpeech: "interjection", definition: "Indicates hesitation", image: "uh", wiki: "https://en.wikipedia.org/wiki/Speech_disfluency")
    private var _um = ScrabbleWord(word: "Um", partOfSpeech: "interjection", definition: "Indicates hesitation, see uh", image: "um", wiki: "https://en.wikipedia.org/wiki/Speech_disfluency")
    private var _un = ScrabbleWord(word: "Un", partOfSpeech: "pronoun", definition: "One", image: "un", wiki: "https://en.wiktionary.org/wiki/un#Noun")
    private var _up = ScrabbleWord(word: "Up", partOfSpeech: "adverb", definition: "A higher position", image: "up", wiki: "https://en.wikipedia.org/wiki/Relative_direction")//https://pixabay.com/en/rock-climbing-fitness-sports-cliff-924842/
    private var _us = ScrabbleWord(word: "Us", partOfSpeech: "pronoun", definition: "Refers to speaker and other person(s) as object of a verb or preposition", image: "us", wiki: "https://en.wiktionary.org/wiki/us#Pronoun")//https://pixabay.com/en/group-people-teens-young-friends-1262146/
    private var _ut = ScrabbleWord(word: "Ut", partOfSpeech: "noun", definition: "The original first note in music scale, now replaced by 'do'", image: "ut", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge#Origin")
    private var _we = ScrabbleWord(word: "We", partOfSpeech: "pronoun", definition: "Used to indicate oneself and another person or persons", image: "we", wiki: "https://en.wiktionary.org/wiki/we#Pronoun")//https://pixabay.com/en/children-smiling-asian-filipino-597471/
    private var _wo = ScrabbleWord(word: "Wo", partOfSpeech: "noun", definition: "Woe, great affliction", image: "wo", wiki: "https://en.wiktionary.org/wiki/wo#Etymology_2")//https://www.pexels.com/photo/man-person-portrait-old-9824/
    private var _xi = ScrabbleWord(word: "Xi", partOfSpeech: "noun", definition: "14th letter of Greek alphabet", image: "xi", wiki: "https://en.wikipedia.org/wiki/Xi_(letter)") //https://commons.wikimedia.org/wiki/File:Xi_uc_lc.svg
    private var _xu = ScrabbleWord(word: "Xu", partOfSpeech: "noun", definition: "Vietnamese monetary unit, worth one hundredth of a dong", image: "xu", wiki: "https://en.wikipedia.org/wiki/Vietnamese_dong")//https://commons.wikimedia.org/wiki/File:Vietnam_1_dong.jpg
    private var _ya = ScrabbleWord(word: "Ya", partOfSpeech: "pronoun", definition: "You, informal", image: "ya", wiki: "https://en.wiktionary.org/wiki/ya#Pronoun")//https://pixabay.com/en/finger-guy-i-want-you-man-point-1299243/
    private var _ye = ScrabbleWord(word: "Ye", partOfSpeech: "pronoun", definition: "Plural form of thou, old English", image: "ye", wiki: "https://en.wikipedia.org/wiki/Ye_(pronoun)")
    private var _yo = ScrabbleWord(word: "Yo", partOfSpeech: "exclamation", definition: "Greeting slang", image: "yo", wiki: "https://en.wikipedia.org/wiki/Yo")//https://commons.wikimedia.org/wiki/File:DapGreeting.jpg
    private var _za = ScrabbleWord(word: "Za", partOfSpeech: "noun", definition: "Pizza", image: "za", wiki: "https://en.wiktionary.org/wiki/za#Etymology_1")
    
    
    
    func getWord() -> [ScrabbleWord]{
        return [_aa, _ab, _ad, _ae, _ag, _ah, _ai, _al, _am, _an, _ar, _as, _at, _aw, _ax, _ay, _ba, _be, _bi, _bo, _by, _de, _do, _ed, _ef, _eh, _el, _em, _en, _er, _es, _et, _ex, _fa, _fe, _gi, _go, _ha, _he, _hi, _hm, _ho, _id, _if, _in, _is, _it, _jo, _ka, _ki, _la, _li, _lo, _ma, _me, _mi, _mm, _mo, _mu, _my, _na, _ne, _no, _nu, _od, _oe, _of, _oh, _oi, _om, _on, _op, _or, _os, _ow, _ox, _oy, _pa, _pe, _pi, _qi, _re, _sh, _si, _so, _ta, _ti, _to, _uh, _um, _un, _up, _us, _ut, _we, _wo, _xi, _xu, _ya, _ye, _yo, _za]
    }
    
    //
    
        //this holds all the words with urls instead of holding it in App in case I want to go back
    func wordsWithURL(){
//        private var _aa = ScrabbleWord(word: "Aa", partOfSpeech: "noun", definition: "Basaltic lava", image: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Aa_large.jpg", wiki: "https://en.wikipedia.org/wiki/Lava#.CA.BBA.CA.BB.C4.81")
//        private var _ab = ScrabbleWord(word: "Ab", partOfSpeech: "noun", definition: "Stomach muscle", image: "https://pixabay.com/static/uploads/photo/2015/06/24/22/39/anatomy-820792_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/Abdomen")
//        private var _ad = ScrabbleWord(word: "Ad", partOfSpeech: "noun", definition: "Advertisement", image: "https://i.imgsafe.org/414b897.jpg", wiki: "https://en.wikipedia.org/wiki/Advertising")
//        private var _ae = ScrabbleWord(word: "Ae", partOfSpeech: "adjective", definition: "One", image: "https://i.imgsafe.org/2fdc327.jpg", wiki: "https://en.wiktionary.org/wiki/ae#Etymology_1")//https://pixabay.com/en/bagpiper-loch-ness-kilt-tartan-1319161/
//        private var _ag = ScrabbleWord(word: "Ag", partOfSpeech: "adjective", definition: "Relating to agriculture", image: "https://i.imgsafe.org/f42e5cb.jpg", wiki: "https://en.wikipedia.org/wiki/Agriculture")
//        private var _ah = ScrabbleWord(word: "Ah", partOfSpeech: "interjection", definition: "An exclamation used to express realization or happiness", image: "https://pixabay.com/static/uploads/photo/2016/04/08/00/28/notion-1315284_960_720.jpg", wiki: "https://en.wiktionary.org/wiki/ah#Interjection")
//        private var _ai = ScrabbleWord(word: "Ai", partOfSpeech: "noun", definition: "Three clawed sloth", image: "https://i.imgsafe.org/2d3ea3b.jpg", wiki: "https://en.wikipedia.org/wiki/Maned_sloth")
//        private var _al = ScrabbleWord(word: "Al", partOfSpeech: "noun", definition: "Indian shrub", image: "https://i.imgsafe.org/4dcae3c.jpg", wiki: "https://en.wiktionary.org/wiki/al#Noun")
//        private var _am = ScrabbleWord(word: "Am", partOfSpeech: "verb", definition: "To exist", image: "https://i.imgsafe.org/6e06aa6.jpg", wiki: "https://en.wikipedia.org/wiki/Cogito_ergo_sum")
//        private var _an = ScrabbleWord(word: "An", partOfSpeech: "indef. article", definition: "Indefinite article placed before words beginning with a vowel sound", image: "https://i.imgsafe.org/8e0a70c.jpg", wiki: "https://en.wikipedia.org/wiki/English_articles#Indefinite_article")//https://pixabay.com/en/ant-cistus-flowers-1203494/
//        private var _ar = ScrabbleWord(word: "Ar", partOfSpeech: "noun", definition: "Letter R", image: "https://pixabay.com/static/uploads/photo/2014/09/18/22/42/letters-451521_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/R")//https://upload.wikimedia.org/wikipedia/commons/b/be/Bonney%2C_Anne_%281697-1720%29.jpg
//        private var _as = ScrabbleWord(word: "As", partOfSpeech: "adverb", definition: "Used in comparing", image: "https://pixabay.com/static/uploads/photo/2015/10/11/19/34/scales-of-justice-982903_960_720.jpg", wiki: "https://en.wiktionary.org/wiki/as#Adverb")
//        private var _at = ScrabbleWord (word: "At", partOfSpeech: "preposition", definition: "Expressing time or place", image: "https://i.imgsafe.org/0cf11a9.jpg", wiki: "https://en.wiktionary.org/wiki/at#Preposition")
//        private var _aw = ScrabbleWord(word: "Aw", partOfSpeech: "exclamation", definition: "Way of expressing sympathy or protest", image: "https://i.imgsafe.org/13711a3.jpg", wiki: "https://en.wiktionary.org/wiki/aw#Interjection")//https://pixabay.com/en/child-face-pouting-stroller-1377126/
//        private var _ax = ScrabbleWord(word: "Ax", partOfSpeech: "noun", definition: "Tool used to chop wood", image: "https://i.imgsafe.org/40295ad.jpg", wiki: "https://en.wikipedia.org/wiki/Axe")//https://pixabay.com/static/uploads/photo/2015/10/12/14/56/axe-984008_960_720.jpg
//        private var _ay = ScrabbleWord(word: "Ay", partOfSpeech: "noun", definition: "Affirmative answer", image: "https://pixabay.com/static/uploads/photo/2015/05/18/23/19/gesture-772977_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/Yes_and_no#Colloquial_forms")
//        private var _ba = ScrabbleWord(word: "Ba", partOfSpeech: "noun", definition: "In ancient Egypt this was one of five parts of the soul", image: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Egyptian_-_Ba_Bird_-_Walters_571472.jpg", wiki: "https://en.wikipedia.org/wiki/Ancient_Egyptian_concept_of_the_soul")
//        private var _be = ScrabbleWord(word: "Be", partOfSpeech: "verb", definition: "Exist, first person singular", image: "https://pixabay.com/static/uploads/photo/2014/03/12/09/24/art-painting-285919_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/The_Creation_of_Adam")
//        private var _bi = ScrabbleWord(word: "Bi", partOfSpeech: "noun", definition: "Bisexual", image: "https://i.imgsafe.org/71417dc.jpg", wiki: "https://en.wikipedia.org/wiki/Bisexuality")
//        private var _bo = ScrabbleWord(word: "Bo", partOfSpeech: "noun", definition: "Pal", image: "https://i.imgsafe.org/91a1844.jpg", wiki: "https://en.wiktionary.org/wiki/bo#Noun")
//        private var _by = ScrabbleWord(word: "By", partOfSpeech: "adverb", definition: "Near or through", image: "https://i.imgsafe.org/bb99d22.jpg", wiki: "https://en.wiktionary.org/wiki/by#Preposition")
//        private var _de = ScrabbleWord(word: "De", partOfSpeech: "preposition", definition: "From, used in names", image: "https://i.imgsafe.org/dad53bd.jpg", wiki: "https://en.wikipedia.org/wiki/Miguel_de_Cervantes")//https://en.wikipedia.org/wiki/Miguel_de_Cervantes
//        private var _do = ScrabbleWord(word: "Do", partOfSpeech: "verb", definition: "To perform an action", image: "https://pixabay.com/static/uploads/photo/2014/04/05/11/40/poster-316691_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/We_Can_Do_It!")
//        private var _ed = ScrabbleWord(word: "Ed", partOfSpeech: "noun", definition: "Education", image: "https://pixabay.com/static/uploads/photo/2015/10/30/09/18/square-academic-cap-1013557_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/Education")
//        private var _ef = ScrabbleWord(word: "Ef", partOfSpeech: "noun", definition: "Letter F", image: "https://pixabay.com/static/uploads/photo/2013/07/14/04/53/alphabet-162574_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/F")
//        private var _eh = ScrabbleWord(word: "Eh", partOfSpeech: "interjection", definition: "Used when a listener does not understand something", image: "https://i.imgsafe.org/0371435.jpg", wiki: "https://en.wikipedia.org/wiki/Eh") //https://en.wikipedia.org/wiki/Flag_of_Canada
//        private var _el = ScrabbleWord(word: "El", partOfSpeech: "noun", definition: "Letter L", image: "https://pixabay.com/static/uploads/photo/2013/07/14/04/54/alphabet-162581_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/L")
//        private var _em = ScrabbleWord(word: "Em", partOfSpeech: "noun", definition: "Printer's measurement", image: "https://i.imgsafe.org/1bb75b4.jpg", wiki: "https://en.wikipedia.org/wiki/Em_(typography)")
//        private var _en = ScrabbleWord(word: "En", partOfSpeech: "noun", definition: "Half an em", image: "https://i.imgsafe.org/2fc1b1b.jpg", wiki: "https://en.wikipedia.org/wiki/En_(typography)")
//        private var _er = ScrabbleWord(word: "Er", partOfSpeech: "interjection", definition: "Sound indicating hesitation", image: "https://i.imgsafe.org/491ed1c.jpg", wiki: "https://en.wiktionary.org/wiki/er#Interjection")
//        private var _es = ScrabbleWord(word: "Es", partOfSpeech: "noun", definition: "Letter S", image: "https://pixabay.com/static/uploads/photo/2013/07/14/04/54/alphabet-162586_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/S")
//        private var _et = ScrabbleWord(word: "Et", partOfSpeech: "verb", definition: "Past tense of eat", image: "https://i.imgsafe.org/5df1c21.jpg", wiki: "https://en.wiktionary.org/wiki/et#Etymology_2")
//        private var _ex = ScrabbleWord(word: "Ex", partOfSpeech: "noun", definition: "Letter X", image: "https://pixabay.com/static/uploads/photo/2013/07/14/04/55/alphabet-162592_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/X")
//        private var _fa = ScrabbleWord(word: "Fa", partOfSpeech: "noun", definition: "Fourth note in music scale", image: "https://i.imgsafe.org/79c157b.jpg", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge")
//        private var _fe = ScrabbleWord(word: "Fe", partOfSpeech: "noun", definition: "Hebrew letter, pronounced as 'Ph' or 'F'", image: "https://i.imgsafe.org/90a359a.jpg", wiki: "https://en.wikipedia.org/wiki/Pe_(letter)#Fe")    //https://commons.wikimedia.org/wiki/File:Hebrew_letter_pe_freefonts.svg
//        private var _gi = ScrabbleWord(word: "Gi", partOfSpeech: "noun", definition: "Clothing worn for Judo", image: "https://i.imgsafe.org/7fd548e.jpg", wiki: "https://en.wikipedia.org/wiki/Judogi") //pixabay
//        private var _go = ScrabbleWord(word: "Go", partOfSpeech: "verb", definition: "To depart", image: "https://i.imgsafe.org/bb2e411.jpg", wiki: "https://en.wikipedia.org/wiki/Go_(verb)")    //pexel
//        private var _ha = ScrabbleWord(word: "Ha", partOfSpeech: "exclamation", definition: "A sound made when surprised", image: "https://pixabay.com/static/uploads/photo/2012/02/29/12/12/cute-18927_960_720.jpg", wiki: "https://en.wiktionary.org/wiki/ha#Interjection")  //pixabay
//        private var _he = ScrabbleWord(word: "He", partOfSpeech: "noun", definition: "Male", image: "https://i.imgsafe.org/db212b4.jpg", wiki: "https://en.wikipedia.org/wiki/He") //pixabay
//        private var _hi = ScrabbleWord(word: "Hi", partOfSpeech: "exclamation", definition: "Used as a greeting", image: "https://i.imgsafe.org/219d849.jpg", wiki: "https://en.wiktionary.org/wiki/hi#Interjection") //publicdomainpictures.net
//        private var _hm = ScrabbleWord(word: "Hm", partOfSpeech: "interjection", definition: "Denotes pondering", image: "https://i.imgsafe.org/3e264c8.jpg", wiki: "https://en.wiktionary.org/wiki/hm#Interjection") //https://pixabay.com/static/uploads/photo/2016/04/01/23/35/art-1301872_960_720.png
//        private var _ho = ScrabbleWord(word: "Ho", partOfSpeech: "interjection", definition: "Used to bring attention, used by Santa", image: "https://pixabay.com/static/uploads/photo/2015/12/13/14/25/christmas-1091178_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/Ho_ho_ho") //pixabay
//        private var _id = ScrabbleWord(word: "Id", partOfSpeech: "noun", definition: "Part of psyche desiring pleasure, Sigmund Freud theory", image: "https://pixabay.com/static/uploads/photo/2014/07/23/19/25/sigmund-freud-400399_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/Id,_ego_and_super-ego#Id")  //pixabay
//        private var _if = ScrabbleWord(word: "If", partOfSpeech: "conjunction", definition: "In the event that", image: "https://i.imgsafe.org/600ef6f.jpg", wiki: "https://en.wikipedia.org/wiki/Flying_pig")    //pixabay https://pixabay.com/en/graffiti-funny-building-painted-386495/
//        private var _in = ScrabbleWord(word: "In", partOfSpeech: "preposition", definition: "Inside", image: "https://i.imgsafe.org/74c8a7a.jpg", wiki: "https://en.wikipedia.org/wiki/Arnolfini_Portrait") // https://pixabay.com/en/belly-painting-baby-pregnant-409794/
//        private var _is = ScrabbleWord(word: "Is", partOfSpeech: "verb", definition: "Third person singular of be", image: "https://i.imgsafe.org/95b3081.jpg", wiki: "https://en.wikipedia.org/wiki/Life") //https://pixabay.com/en/life-is-beautiful-courage-joy-hope-905867/
//        private var _it = ScrabbleWord(word: "It", partOfSpeech: "noun", definition: "Designated person in a child's game", image: "https://i.imgsafe.org/b2ea217.jpg", wiki: "https://en.wikipedia.org/wiki/Tag_(game)")//https://pixabay.com/en/blindfolded-chase-game-search-kids-37705/
//        private var _jo = ScrabbleWord(word: "Jo", partOfSpeech: "noun", definition: "Sweetheart, used in Scotland", image: "https://pixabay.com/static/uploads/photo/2016/04/30/21/41/couple-1363993_960_720.jpg", wiki: "https://en.wiktionary.org/wiki/jo#Noun")
//        private var _ka = ScrabbleWord(word: "Ka", partOfSpeech: "noun", definition: "Part of spirit which remains in a mummy", image: "https://upload.wikimedia.org/wikipedia/commons/5/54/Ka_Statue_of_horawibra.jpg", wiki: "https://en.wikipedia.org/wiki/Ancient_Egyptian_concept_of_the_soul#Ka_.28vital_spark.29")
//        private var _ki = ScrabbleWord(word: "Ki", partOfSpeech: "noun", definition: "Synonymous with qi", image: "https://pixabay.com/static/uploads/photo/2014/10/09/14/02/woman-481902_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/Qi")
//        private var _la = ScrabbleWord(word: "La", partOfSpeech: "noun", definition: "Sixth note in music scale", image: "https://i.imgsafe.org/d0a1168.jpg", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge") //https://pixabay.com/en/piano-midi-music-musical-773735/
//        private var _li = ScrabbleWord(word: "Li", partOfSpeech: "noun", definition: "Chinese measurement of distance, about .5 km", image: "https://i.imgsafe.org/e16e461.jpg", wiki: "https://en.wikipedia.org/wiki/Li_(unit)") //https://www.pexels.com/photo/mountains-clouds-historical-great-wall-of-china-19872/
//        private var _lo = ScrabbleWord(word: "Lo", partOfSpeech: "exclamation", definition: "Said when desiring attention, used in religous texts", image: "https://i.imgsafe.org/f21bff3.jpg", wiki: "https://en.wiktionary.org/wiki/lo#Interjection") //https://pixabay.com/en/moses-jesus-wanderer-prophet-145721/
//        private var _ma = ScrabbleWord(word: "Ma", partOfSpeech: "noun", definition: "Mother", image: "https://i.imgsafe.org/ffaa720.jpg", wiki: "https://en.wikipedia.org/wiki/Mother") //https://www.pexels.com/photo/woman-female-girl-child-8986/
//        private var _me = ScrabbleWord(word: "Me", partOfSpeech: "pronoun", definition: "Referring to self", image: "https://i.imgsafe.org/0e1b106.jpg", wiki: "https://en.wiktionary.org/wiki/me#Pronoun")//https://pixabay.com/en/penguin-zoo-conceited-844834/
//        private var _mi = ScrabbleWord(word: "Mi", partOfSpeech: "noun", definition: "Third note in music scale", image: "https://i.imgsafe.org/29d3b6e.jpg", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge")
//        private var _mm = ScrabbleWord(word: "Mm", partOfSpeech: "interjection", definition: "Used to convey one's pleasure", image: "https://i.imgsafe.org/475f1bb.jpg", wiki: "https://en.wiktionary.org/wiki/mm#Interjection")//https://pixabay.com/en/ice-man-happy-eating-relax-party-375361/
//        private var _mo = ScrabbleWord(word: "Mo", partOfSpeech: "noun", definition: "Short amount of time", image: "https://i.imgsafe.org/5f4958e.jpg", wiki: "https://en.wikipedia.org/wiki/Moment_(time)") //https://pixabay.com/en/hourglass-time-pressure-time-708574/
//        private var _mu = ScrabbleWord(word: "Mu", partOfSpeech: "noun", definition: "12th letter of the Greek alphabet", image: "https://i.imgsafe.org/6d6f15d.jpg", wiki: "https://en.wikipedia.org/wiki/Mu_(letter)") //https://commons.wikimedia.org/wiki/File:Mu_uc_lc.svg
//        private var _my = ScrabbleWord(word: "My", partOfSpeech: "pronoun", definition: "Possessive I", image: "https://i.imgsafe.org/7d4e444.jpg", wiki: "https://en.wiktionary.org/wiki/my#Etymology_1") //http://digitalcollections.nypl.org/items/510d47df-f072-a3d9-e040-e00a18064a99
//        private var _na = ScrabbleWord(word: "Na", partOfSpeech: "adverb", definition: "Not", image: "https://i.imgsafe.org/92540c9.jpg", wiki: "https://en.wiktionary.org/wiki/na#Interjection") //https://www.pexels.com/photo/hand-thumbs-up-thumb-black-and-white-8252/
//        private var _ne = ScrabbleWord(word: "Ne", partOfSpeech: "adjective", definition: "Birthname - Marilyn Monroe, ne Norma Mortenson", image: "https://i.imgsafe.org/ade443b.jpg", wiki: "https://en.wikipedia.org/wiki/Given_name#Name_at_birth") //https://commons.wikimedia.org/wiki/File:Marilyn_Monroe_photo_pose_Seven_Year_Itch.jpg
//        private var _no = ScrabbleWord(word: "No", partOfSpeech: "determiner", definition: "None", image: "https://i.imgsafe.org/bdabdc7.jpg", wiki: "https://en.wikipedia.org/wiki/Yes_and_no") //https://pixabay.com/en/no-hunting-sign-no-hunting-fence-1110491/   https://pixabay.com/en/stop-no-photo-no-photographing-hand-565609/
//        private var _nu = ScrabbleWord(word: "Nu", partOfSpeech: "noun", definition: "13th letter of the Greek alphabet", image: "https://i.imgsafe.org/44f41e9.jpg", wiki: "https://en.wikipedia.org/wiki/Nu_(letter)") //https://commons.wikimedia.org/wiki/File:Nu_uc_lc.svg
//        private var _od = ScrabbleWord(word: "Od", partOfSpeech: "noun", definition: "Odic force, hypothetical force believed to transcend throughout nature", image: "https://i.imgsafe.org/e2dae07.jpg", wiki: "https://en.wikipedia.org/wiki/Odic_force") //https://pixabay.com/en/star-wars-flower-soldier-dark-1176168/
//        private var _oe = ScrabbleWord(word: "Oe", partOfSpeech: "noun", definition: "Winds from the Faroe Islands", image: "https://i.imgsafe.org/fa3512f.jpg", wiki: "https://en.wikipedia.org/wiki/Faroe_Islands#Climate") //https://pixabay.com/en/crooklets-beach-cornwall-bude-1313636/
//        private var _of = ScrabbleWord(word: "Of", partOfSpeech: "preposition", definition: "Indicates something belonging to something else", image: "https://i.imgsafe.org/0c19367.jpg", wiki: "https://en.wiktionary.org/wiki/of#Preposition") //http://res.cloudinary.com/di6su8dza/image/upload/v1463118575/puzzle-654110_1280_s51zu6.jpg
//        private var _oh = ScrabbleWord(word: "Oh", partOfSpeech: "exclamation", definition: "Exclamed during moments of sorrow, happiness, or anger", image: "https://i.imgsafe.org/23b1995.jpg", wiki: "https://en.wiktionary.org/wiki/oh")//https://pixabay.com/en/photographer-man-hands-characters-1210218/
//        private var _oi = ScrabbleWord(word: "Oi", partOfSpeech: "exclamation", definition: "Said to try to gain a person's attention", image: "https://i.imgsafe.org/3d83fcd.jpg", wiki: "https://en.wikipedia.org/wiki/Oi_(interjection)") //https://www.flickr.com/photos/prblmtkx/22845310843/in/photolist-ANLbZH-uctXYG-ow8ti1-qbNw3e-otvM2c-ornWVj-ouXAsB-obP2U8-oeZbCd-obMVPW-of27Ad-owHJLB-odFGDZ-oc7Jtb-osYxmL-obZ8Pg-ouXTf6-odjQmA-orp4vG-obWjz9-otsmBh-ouWeWh-of2s75-odZsVQ-odZFm1-ovh91m-osYcuw-obw2U2-of27Pu-odueE8-obVozh-ouKMNY-osHE4n-oc8Qhc-odtk3M-otpimJ-oqXMjy-owWeR6-osUR5i-osHoGk-ouKT7y-osPS5u-ovhsbj-ot7LrM-obv6HZ-otcwpP-otoDKj-otha2w-oc8ufv-ouXWAz
//        private var _om = ScrabbleWord(word: "Om", partOfSpeech: "noun", definition: "Sound made during meditation", image: "https://i.imgsafe.org/5629cd9.jpg", wiki: "https://en.wikipedia.org/wiki/Om")//https://www.pexels.com/photo/relaxation-relaxing-meditation-yoga-12344/
//        private var _on = ScrabbleWord(word: "On", partOfSpeech: "preposition", definition: "In contact with another object", image: "https://i.imgsafe.org/65ac5f8.jpg", wiki: "https://en.wiktionary.org/wiki/on#Adjective")//https://www.pexels.com/photo/mountains-nature-sky-sunny-6629/
//        private var _op = ScrabbleWord(word: "Op", partOfSpeech: "noun", definition: "Type of art with optical illusions", image: "https://i.imgsafe.org/7a4d8c3.jpg", wiki: "https://en.wikipedia.org/wiki/Op_art")//https://pixabay.com/en/optical-illusion-chessboard-tunnel-155520/
//        private var _or = ScrabbleWord(word: "Or", partOfSpeech: "noun", definition: "Color of gold used in armorial bearings during the middle ages", image: "https://i.imgsafe.org/9b9a359.jpg", wiki: "https://en.wikipedia.org/wiki/Or_(heraldry)")//https://pixabay.com/en/benferri-coat-of-arms-heraldry-906563/
//        private var _os = ScrabbleWord(word: "Os", partOfSpeech: "noun", definition: "A bone", image: "https://i.imgsafe.org/b0bd766.jpg", wiki: "https://en.wiktionary.org/wiki/os#English")//https://pixabay.com/en/bone-animal-decay-skeleton-nature-949077/
//        private var _ow = ScrabbleWord(word: "Ow", partOfSpeech: "exclamation", definition: "Said when one feels abrupt pain", image: "https://i.imgsafe.org/bf58180.jpg", wiki: "https://en.wiktionary.org/wiki/ow#Interjection")//https://pixabay.com/en/doctor-pain-vaccination-shot-arm-673578/
//        private var _ox = ScrabbleWord(word: "Ox", partOfSpeech: "noun", definition: "Castrated male cattle", image: "https://i.imgsafe.org/d07cb35.jpg", wiki: "https://en.wikipedia.org/wiki/Ox")//https://pixabay.com/en/swot-up-cattle-farm-nature-1261538/
//        private var _oy = ScrabbleWord(word: "Oy", partOfSpeech: "exclamation", definition: "variable of oi", image: "https://upload.wikimedia.org/wikipedia/commons/6/60/Town_crier%2C_Plymouth%2C_Devon%2C_England_-_20101030.jpg", wiki: "https://en.wikipedia.org/wiki/Town_crier")
//        private var _pa = ScrabbleWord(word: "Pa", partOfSpeech: "noun", definition: "Father", image: "https://i.imgsafe.org/edec9bf.jpg", wiki: "https://en.wikipedia.org/wiki/Father") //https://pixabay.com/en/father-son-smile-laugh-happy-dad-849092/
//        private var _pe = ScrabbleWord(word: "Pe", partOfSpeech: "noun", definition: "Hebrew letter, pronounced as 'P'", image: "https://i.imgsafe.org/fe8fc9a.jpg", wiki: "https://en.wikipedia.org/wiki/Pe_(letter)")
//        private var _pi = ScrabbleWord(word: "Pi", partOfSpeech: "noun", definition: "16th letter of Greek alphabet", image: "https://i.imgsafe.org/10d8dab.jpg", wiki: "https://en.wikipedia.org/wiki/Pi_(letter)")//https://pixabay.com/en/pi-symbol-letter-mathematics-math-1327145/
//        private var _qi = ScrabbleWord(word: "Qi", partOfSpeech: "noun", definition: "A life force in Chinesse medicine which flows throughout the body", image: "https://i.imgsafe.org/2b5ab1b.jpg", wiki: "https://en.wikipedia.org/wiki/Qi")//https://www.pexels.com/photo/people-festival-sitting-freedom-50709/
//        private var _re = ScrabbleWord(word: "Re", partOfSpeech: "noun", definition: "Second note in music scale", image: "https://i.imgsafe.org/3da2e3c.jpg", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge")
//        private var _sh = ScrabbleWord(word: "Sh", partOfSpeech: "interjection", definition: "Used when desiring silence", image: "https://i.imgsafe.org/547effd.jpg", wiki: "https://en.wiktionary.org/wiki/sh#Interjection")//https://pixabay.com/en/person-human-child-girl-blond-976759/
//        private var _si = ScrabbleWord(word: "Si", partOfSpeech: "noun", definition: "Seventh note in music scale, also known as Ti", image: "https://i.imgsafe.org/65aa839.jpg", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge")
//        private var _so = ScrabbleWord(word: "So", partOfSpeech: "noun", definition: "Fifth note in music scale", image: "https://i.imgsafe.org/78b3044.jpg", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge")
//        private var _ta = ScrabbleWord(word: "Ta", partOfSpeech: "exclamation", definition: "Thank you", image: "https://i.imgsafe.org/8b422eb.jpg", wiki: "https://en.wiktionary.org/wiki/ta#Interjection")//https://pixabay.com/en/thanks-gratitude-smile-appreciation-1209247/
//        private var _ti = ScrabbleWord(word: "Ti", partOfSpeech: "noun", definition: "Seventh note in music scale", image: "https://i.imgsafe.org/9a0c9ae.jpg", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge")
//        private var _to = ScrabbleWord(word: "To", partOfSpeech: "preposition", definition: "Indicates something that a person or objects moves toward", image: "https://pixabay.com/static/uploads/photo/2015/09/18/07/44/ocean-945148_960_720.jpg", wiki: "https://en.wiktionary.org/wiki/to#Particle")
//        private var _uh = ScrabbleWord(word: "Uh", partOfSpeech: "interjection", definition: "Indicates hesitation", image: "https://pixabay.com/static/uploads/photo/2014/04/05/11/19/unsure-315080_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/Speech_disfluency")
//        private var _um = ScrabbleWord(word: "Um", partOfSpeech: "interjection", definition: "Indicates hesitation, see uh", image: "https://pixabay.com/static/uploads/photo/2016/02/15/23/08/unsure-1202301_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/Speech_disfluency")
//        private var _un = ScrabbleWord(word: "Un", partOfSpeech: "pronoun", definition: "One", image: "https://pixabay.com/static/uploads/photo/2013/07/12/13/11/one-146653_960_720.jpg", wiki: "https://en.wiktionary.org/wiki/un#Noun")
//        private var _up = ScrabbleWord(word: "Up", partOfSpeech: "adverb", definition: "To a higher position", image: "https://i.imgsafe.org/ba97d94.jpg", wiki: "https://en.wikipedia.org/wiki/Relative_direction")//https://pixabay.com/en/rock-climbing-fitness-sports-cliff-924842/
//        private var _us = ScrabbleWord(word: "Us", partOfSpeech: "pronoun", definition: "Refers to speaker and other person(s) as object of a verb or preposition", image: "https://i.imgsafe.org/cbae304.jpg", wiki: "https://en.wiktionary.org/wiki/us#Pronoun")//https://pixabay.com/en/group-people-teens-young-friends-1262146/
//        private var _ut = ScrabbleWord(word: "Ut", partOfSpeech: "noun", definition: "The original first note in music scale, now replaced by 'do'", image: "https://i.imgsafe.org/e9eaa44.jpg", wiki: "https://en.wikipedia.org/wiki/Solf%C3%A8ge#Origin")
//        private var _we = ScrabbleWord(word: "We", partOfSpeech: "pronoun", definition: "Used to indicate oneself and another person or persons", image: "https://i.imgsafe.org/f9dc55e.jpg", wiki: "https://en.wiktionary.org/wiki/we#Pronoun")//https://pixabay.com/en/children-smiling-asian-filipino-597471/
//        private var _wo = ScrabbleWord(word: "Wo", partOfSpeech: "noun", definition: "Woe, great affliction", image: "https://i.imgsafe.org/0b8d814.jpg", wiki: "https://en.wiktionary.org/wiki/wo#Etymology_2")//https://www.pexels.com/photo/man-person-portrait-old-9824/
//        private var _xi = ScrabbleWord(word: "Xi", partOfSpeech: "noun", definition: "14th letter of Greek alphabet", image: "https://i.imgsafe.org/2a30367.jpg", wiki: "https://en.wikipedia.org/wiki/Xi_(letter)") //https://commons.wikimedia.org/wiki/File:Xi_uc_lc.svg
//        private var _xu = ScrabbleWord(word: "Xu", partOfSpeech: "noun", definition: "Vietnamese monetary unit, worth one hundredth of a dong", image: "https://i.imgsafe.org/3bdca21.jpg", wiki: "https://en.wikipedia.org/wiki/Vietnamese_dong")//https://commons.wikimedia.org/wiki/File:Vietnam_1_dong.jpg
//        private var _ya = ScrabbleWord(word: "Ya", partOfSpeech: "pronoun", definition: "You, informal", image: "https://i.imgsafe.org/515ac2f.jpg", wiki: "https://en.wiktionary.org/wiki/ya#Pronoun")//https://pixabay.com/en/finger-guy-i-want-you-man-point-1299243/
//        private var _ye = ScrabbleWord(word: "Ye", partOfSpeech: "pronoun", definition: "Plural form of thou", image: "https://pixabay.com/static/uploads/photo/2012/11/28/11/10/shakespeare-67698_960_720.jpg", wiki: "https://en.wikipedia.org/wiki/Ye_(pronoun)")
//        private var _yo = ScrabbleWord(word: "Yo", partOfSpeech: "exclamation", definition: "Greeting slang", image: "https://i.imgsafe.org/61ac868.jpg", wiki: "https://en.wikipedia.org/wiki/Yo")//https://commons.wikimedia.org/wiki/File:DapGreeting.jpg
//        private var _za = ScrabbleWord(word: "Za", partOfSpeech: "noun", definition: "Pizza", image: "https://i.imgsafe.org/737f9d3.jpg", wiki: "https://en.wiktionary.org/wiki/za#Etymology_1")
    }
    
    
    
}